### ISSUE TITLE
Send Mail

### ISSUE THREAD

**Issue by mhamiache** [signumsoftware/framework#121]
Is there a way to send a mail thought the framework. I will put the subject and email and message straight by code.

Thanks

**Comment by olmobrutall** [comment]
On top of Microsoft SmtpClient the Mailing systems allows you to:
* define templates that get filled with DB info, in multiple languages: 
* keep track of what emails were sent
* send emails asyncronously and transactionally by using a table as queue
* Advanced: receive emails in POP3
What you need?

**Comment by mhamiache** [comment]
I need insde the code to send an email define by me. I dont need to use no template. I want to know if there is something already define and i will just need a regular send mail C# class.

**Comment by mhamiache** [comment]
if i m using creating the emailmessage entity and fill it with whatever i need and i use the function sendemail at the end. will it work?

**Comment by olmobrutall** [comment]
Yes, will work. I recomend you to use SendAsync, this way its just stored in the database as "ReadyToSend" and then by starting the AsyncEmailSender you have a thread sending the emails. 

There are two advantages: 
* The user becomes an answer faster, because sending emails is relatively slow. 
* Sending email becomes transactional, so if an operation Send an email and then something else throws an exception and the user re-tries 5 times you're not sending 5 emails. 

Makes sense?

**Comment by mhamiache** [comment]
Thanks for the answer
