### ISSUE TITLE
DataBase.RetrieveAll<T>() -> Request<>() (Retriever()) -> stack overflow

### ISSUE THREAD

**Issue by modma** [signumsoftware/framework#178]
Hi, I see another problem, In `DataBase.RetrieveAll`, I see a recursive calls to `RealRetriver.Request` maybe caused by cross references to `ProductoMotorEntity`, in the old framework this works perfect, in this moments with the lastest version causes _stack overflow_

![err1](https://cloud.githubusercontent.com/assets/16271691/24042556/ce60fd72-0b12-11e7-9e66-b6fa00653b1d.jpg)

![err2](https://cloud.githubusercontent.com/assets/16271691/24042558/ce6101c8-0b12-11e7-9c65-0583573bbba4.jpg)

![err3](https://cloud.githubusercontent.com/assets/16271691/24042557/ce60fcd2-0b12-11e7-95be-80c658ebc6b0.jpg)

**Comment by olmobrutall** [comment]
Hi modma, thanks for the tip. 

Looks like it happens when retrieving cycles on cached entities. 

This commit should fix the error: 

https://github.com/signumsoftware/framework/commit/8931bec3d5d8ac197c7571945c0add19bf681160

Just take latest version of master. 

BTW: A C# 7 version is comming, consider updating to VS2017

**Comment by modma** [comment]
yes, thank you very much, now works!
The update/migration to 2017 in the near future I do not think very possible at the moment, it depends on the corporation where I work, but perhaps I will try to do something about it
