### ISSUE TITLE
Upgrade to .NET Core?

### ISSUE THREAD

**Issue by crazyants** [signumsoftware/framework#243]

**Comment by olmobrutall** [comment]
Hi Tomny, 

Signum Framework is almost 10 years old but we try to keep it always up to date. 

Currently my plan is: 

* Typescript 2.6 (https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/) with strictFunctionTypes. Almost done. 

* React 16 (https://reactjs.org/blog/2017/09/26/react-v16.0.html). I want to start today, shouldn't take too long. 

* Bootstrap 4 (https://getbootstrap.com/) and reactstrap (https://github.com/reactstrap/reactstrap). It's like 60% already, but more complicated. 

* .Net Core

I haven't rushed into jumping to .Net Core because I saw no clear benefits if you're not using Linux / Mac. 

Also the more time passes, the more compatible  .Net Core gets to .Net Framework, greater Nuget compatibility, better tooling, etc... I also don't expect big changes in the bread and butter of Signum Framework (Entities, Logic, UI) but changes on the plumbing (.csproj, Global.asax, Web.config, etc..)

Anyway, looks like Microsoft is pushing .Net Core hard, .Net Core 2.0 looks complete enough and VS 2017 has already some updates improving tooling, so it's about time to start the jump. 

@JesusFrancesGarcia wanted to start a fork for doing this, maybe you want to help him? I'll join when reactstrap is ready.

**Comment by avifatal** [comment]
I think linux deployment has huge added value. appart from that chasing typescript every few weeks creates overhead for you and the community.
Don't you think?

**Comment by olmobrutall** [comment]
Most of the Signum devs come from a windows only environment, Linux, bash, etc is alien to them (nowadays, also alien for me). But sure, once the possibility is there, some people will use it. Also right now is MS SQL only. Real Linux support requires Postgres or MYSQL. I dont use such an environment at work and will require a hero to champion support for these RDBMS. 

About chasing Typescript, it’s annoying I know, but it’s not only TS, also react, bootstrap etc.. all get upgraded at a different peace with *eventual* coordination...

With the broad scope of the framework, and the current amount of collaborators, I prefer to have a reduced but up-to-date set of technologies as foundation and avoid choices.

**Comment by olmobrutall** [comment]
With Bootstrap 4 already finished (https://github.com/signumsoftware/framework/commit/56e9874c43d1758c6294559758cc4f7532cc215b) the next big technological change will be .NET Core

**Comment by spkyghost** [comment]
Any updates on this topic?

I am totally burning for this to go .NET Core

**Comment by olmobrutall** [comment]
Hi @spkyghost, 

The 'core' branch is finished since a few weeks, but Extensions has a dependency to CNTK that is not ready yet. 

They are working on it so it shouldn't take long. This issue tracks the progress: https://github.com/Microsoft/CNTK/issues/2352

Cheers

**Comment by olmobrutall** [comment]
Hi @spkyghost, .Net Core is ready: https://github.com/signumsoftware/framework/commit/2997541863847ad35cc2a51e97e5c1f2c58f8050#comments
