### ISSUE TITLE
Nullable DateTime field in mixin wont accept null unless you use question mark

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#39]
When applying a datetime field to mixin with nullable attribute you get an exception when you save the entity with null value in the date time.
I dont think it will happened to a regular entity.
This will solve the case (the ? ):
[Nullable]
public DateTime? DateTime {get;set;}
The error and the stack are not on me, if you cant reproduce it, please ask me.

**Comment by olmobrutall** [comment]
If I add the following to UserEmployeeMisin in Southwind everything works as expected:

```C#
[Nullable]
public DateTime? DateTime {get;set;}
```

If I remove the `?` then then... it successfully crashes :) 


The `[Nullable]` attribute is mainly there for completion, but is actually quite useless. 

By default Signum Framework mimics in SQL the same behavior than in C#. Value types will be not-nullable and reference types will be nullable. 

In order to make a not-nullable reference type (like strings, entities, lites, embeddeds) add the `[NotNullable]` attribute.

In order to make a nullable value type (int, decimal, DateTime, Guid...) then make the field type nullable using `?`.

The `[Nullable]` attribute is mainly there for completion, but is actually quite useless. 
99.9% of the cases you represent a nullable column with a nullable type. In the rare case where you have a nullable column in the database that you can not change, but you know that all the entities that will be retrieved/saved/queried will be non-nullable, then the attribute could be handy. I haven't use it yet :)

Hopefully this will be simpler in C# 7 if nullability is unified between value an reference types: https://github.com/dotnet/roslyn/issues/5032
