### ISSUE TITLE
Feature request : Make the UI more single page app alike.

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#40]
Hi.
I have a system with around 40-50 users.
Some of the users are browsing thousands of rows on a daily bases.
When you are in the grid, and you want to view more details, you click on the "View" and then you get redirected  to an other page.
if you are in a ling grid, you loose the context of where you were and which one you clicked on.
My request is instead of redirecting the entire page, just open the form in a modal dialog.

More than that, it will make the app more browsable and fast to work in.
I see 3 use cases.
1. clicking on the view link in the grid.
2. clicking on the related entity in the grid (Users => Roles for example)
3. Creating new entity.

As far as I can see it, since there is no support today, you can leave this config as a single boolean.

If you want to go advanced, you can do the following.
in the AppClient cs file, under the EntitySettings you can add a setting for each entity.
bool ShowCreationFormInModal 
bool ShowGridDetailsInModal

for related Entities you can do this:
bool ShowGridRelatedInModal
or create a function in EntitySettings as the following:
```
public void OpenRelatedEntitiesInModal(params Entity[]);
```
This will allow certain related entities to be opened in a modal.

I hope it was understandable....
Avi

**Comment by olmobrutall** [comment]
Hi Avi,

My main concern with Modal entities is that sometimes an entity is complex enough that does not fit properly in a modal window. 

I liked your idea of putting this information in the EntitySettings. Once you know an entity is 'small enough' then makes sense to open it a popup independently of where it is:

* View link
* Related entitiy
* Create

Another concern is how to style the link. Previously there were inconsistencies between the link styling and behavior and was confusing. Now links are always links, and (->) icons open in popup.

* How should we differentiate the View/Related entity links visually in the SearchControl? 
* What about the Create button? 
* What is the behavior if you have an `ImplementedBy`/`ImplementedByAll` column, like the related entity in an exception?
* What happens if you press `Ctrl+Click` on a Popup-enabled entity? 

If we solve this UI problems the feature should be relatively simple to program, and if proved useful I think should be enabled per-entity without any global configuration. If somebody doesn't like he can foreach all the `EntitySettings` and turn it of.

**Comment by avifatal** [comment]
Hi Olmo.

> My main concern with Modal entities is that sometimes an entity is complex enough that does not fit properly in a modal window.

**Answer**
I dont really agree, in dynamics CRM all forms are opened in a kind of dialog, it looks perfect, even a  very long and complex form. The way you can take care of this is to put the buttons strip as static and the form scrollable bellow it, this way you can always click Save.  you can see here: https://www.epinova.no/PageFiles/8265/dynamics_crm.png the form can be scrolled and the buttons are static.

> How should we differentiate the View/Related entity links visually in the SearchControl?  

**Answer**  I dont understand what do you mean, you can keep the links as today, just change the behavior. or pls explain.

> What about the Create button?

**Answer**  What about it? you can keep the same design... pls explain.

> What is the behavior if you have an ImplementedBy/ImplementedByAll column, like the related entity in an exception?

**Answer**  I just read about this feature, it does makes things a little bit more complex. maybe expose another function like I suggested, see above...

> What happens if you press Ctrl+Click on a Popup-enabled entity?

**Answer** Should always act like today, because this is how browsers acts.

**Comment by avifatal** [comment]
I just thought about another usecase we should cover.
In a form, you have a field with related information like User in exception. this should be covered as Well, in this case, we take the configuration to a more complex place. how about this: 

We put global configuration ShowFormsInModal in the EntityConfiguration.
when ever this is turned on, you render always 2 links, (like in this example: https://jsfiddle.net/jjqnfzgj/embedded/result/) the first one will be modal, and the second one (icon) will be independent window.
this makes the config simpler and makes it supports the 2 ways

**Comment by olmobrutall** [comment]
**Buttons in the top:** 
This is a full screen page. How it should be when in a Modal? I'd to customize the CSS for Bootstrap modals to make them bigger and still they loose 20-30% of the screen area. 


**Double links:**
Exactly this is what I mean, but the other way around. 

The convention now is that a link is a normal link (full screen / new tab) while a [->] button opens a popup. I just don't like the idea of having millions of [->] icons in the SearchControl.

**React?**
Could we think about that in the context of the new React version? What you asking is a big change for many applications and I think the focus should be now in React, where we have more

**Comment by avifatal** [comment]
Hi Olmo.
**Buttons in the top:**
it is not, see this: ![D Crm](http://magwebsitefiles2015.blob.core.windows.net/blogfiles/blog-images-9/2011_Marketing_Lists_1.jpg?sfvrsn=0 ) its a kind of modal modal.
you can make the buttons a little bit smaller...

**Double links:**
I think this will reduce the amount of config and your work.

**React?**
From my world, (the Angular js world), it should be supported as well in react, the same way. I dont see any code going to be thrown away.
Its too important to our users, loosing the context when you work in a system is a big disadvantage, since there will be no change in react, I would love to see it as soon as you can, considering it is relatively easy.

Thanks

**Comment by olmobrutall** [comment]
What you showing is not a modal popup, but an independent IE window. This is what you looking for?. 

What I mean with React was not to do it in React as well, but do it in React instead. Since React is going to be a build from the ground up, not as an evolution of Signum.Web, I can not invest a lot of time in moving Signum.Web forward since A) I don't have so much time and B) otherwise no one will move. 

The change is not complicated but also not so trivial to solve it properly. If you need it soon, could you try to build a prototype? I can help you understanding the different moving parts.

**Comment by avifatal** [comment]
No no, this is just an example for how a form can be very long and still it buttons are functioning. let leave that. the bootstrap modal is what we are after.

What is the release date for the react (production)

Please explain about the prototype or send me a ling to an example of what you want?
Thanks

**Comment by olmobrutall** [comment]
This issue is already solved
