### ISSUE TITLE
Or statement in search criteria on the UI

### ISSUE THREAD

**Issue by avifatal** [signumsoftware/framework#41]
Hi,
As for today the app supports "and" scenarios, so the or statement is only going via server side coding.

The or statement ui is much more complicated, but can be overcome in a modal window.
Here is a good example of full query example: http://demos.telerik.com/aspnet-ajax/filter/examples/overview/defaultcs.aspx

People tends to think that or statement is needed because of bad data modeling, in the real world, you find yourself very early with this need (as an end user).
Thanks

**Comment by olmobrutall** [comment]
### The case for ORs

ORs are a singularity in the expressive power of the SearchControl (not the LINQ provider). The SearchControl started with ANDs of Column-Operation-Value, then it added JOINs, Collections with Any, All, Element, but never ORs. The reason is UI: 

Most of what I heard from users until they get used is that the SearchControl is complicated, that's why most of the power is hidden in the sequence of Combo Boxes, but this won't work for ORs. 

The Telerik approach is quite complicated in its own, with two + buttons hard to differentiate. Also, it's still incomplete since you can not express something like `NOT(Order = 1 OR Order = 2)`. Adding `OR` without adding `NOT` is incomplete. 

Anyway, we would have added OR if we wouldn't have found a way of circumvent the problems in other ways: 

#### Creating an Expression in C#. 

This way you encapsulate a reusable business concept. 

i.e: Convert `User.Name == "Devil" OR  User.Name == "Satan"` to `User.IsBadGuy`

#### Using `In`/`NotIn` 
 
Unfortunately this is only available for Signum.Windows right now.

i.e: Convert `User.Name == "Devil" OR  User.Name == "Satan"` to `User.Name IN ["Devil", "Satan"]`

#### Creating dynamic User Expressions (idea for the future)

There is the idea that you can register custom user expressions for different entities. For example by having a `[Add new...]` at the button of every Query Token combo box that prompts a modal where you can write C# and save the expression. 

Will be challenging to synchronize however.

**Comment by avifatal** [comment]
Hi Olmo.
> Creating an Expression in C#.

If we make it wok with a new release, its a problem.
Users should be able to build there own queries. or if its too complicated, the sys admin (not a programmer) should solve it for them...

> Using In/NotIn
Is this available for all kind of fields (related entities?)? Do you think it is covering most of the "Or" use cases?


> Creating dynamic User Expressions (idea for the future)

I would do something else, but its huge as far as i see it,
Create a new query language SFQL Signum Frameqork Query Language and let the user build queries with crazy autocomplete.
New Relic (app monitoring cloud) did something very useful, you can build queries in their web ui.

![NRQL](https://cms-assets.tutsplus.com/uploads/users/317/posts/22448/image/nrql-autofill.jpg)
 
 But this is really long shot.

**Comment by olmobrutall** [comment]
Hi
> Creating an expression tree

Of course this should only be used for important concepts that deserve a release, but very often the same expression that the users needs is necessary in other parts for the business logic. 

> Using In/NotIn

If works for entities and values, yes. You can add more values with a (+) button or remove values with (x). I've received request to allow including many values separated by comma instead of adding them one by one with the buttons. 

I do think that this removes many examples where OR is needed without complicating the UI. Users also have problems to build boolean expressions. 

*i.e.: Saying `Sex = Man AND Sex = Woman` to mean `Sex = Man UNION Sex = Woman` that should be expressed `Sex = Man UNION Sex = Woman`.

> NRQL

I like the idea of having a more textual way of expressing the query. Probably will be faster to edit, change, etc... and will support arbitrary boolean expressions more gracefully. I just hope that users don't get too scared. 

This approach will have other challenges. It fits nicely for WHERE but not so nice for new columns/ charting columns.

UserQueries and UserCharts will also be affected: No longer a list of filter but a tree, or a parseable text area. 

An approach that I like more is an editable combobox where you can write. Will make the UI faster, just as discoverable, but not more expressive.

**Comment by avifatal** [comment]
Do you have plans to implement the "in/not in" on the Web framework?

**Comment by olmobrutall** [comment]
For me, it's clear that the new React / TypeScript stack is the best solution moving forward and it's where I'm going to focus my free time. Is a massive undertake and any help will be appreciated. https://github.com/signumsoftware/framework/wiki/Signum-React 

In/Not In for web should take something like 1-2 days of development. I can orient anybody that wants to take the task and accept pull request.

**Comment by olmobrutall** [comment]
### `In`/`NotIn` works on `Signum.React`! :smile: 

![image](https://cloud.githubusercontent.com/assets/720953/13034802/b07ff1fc-d33f-11e5-89cd-8ba9d07a2987.png)

Unfortunately, a lot of other things don't work jet there.

**Comment by avifatal** [comment]
sounds very good. looking forward to see the RC
