### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#52]
Hi Olmo and the community,
I need help in creating tabs on an entity page, how do I go about it, please?

**Comment by mapacheL** [comment]
Hi, you can insert the tabs in the usual way, for twitter bootstrap using a ul tag with the class "nav nav-tabs": http://getbootstrap.com/components/#nav-tabs

**Comment by roiez** [comment]
thank you Luis

**Comment by roiez** [comment]
thank you Luis, but this only works in views, what I need is to have tabs on an entity search window, and also only in one, not all of my search entity windows.

**Comment by olmobrutall** [comment]
Hi roiez, I'm back from holidays. 

While the raw bootstrap tabs work, there is also a signum-specific HtmlHelper for creating the tabs that has two main benefits: 

* Instead of a list of headers and a list of contents, promotes a list of tabs, each with a header and a content. This way the code is more cohesive and it's cleaner to conditionally hide tabs. 

Unfortunately southwind doesn't have an example but maybe the source code gives you an idea:

https://github.com/signumsoftware/framework/blob/master/Signum.Web/HtmlHelpers/HtmlHelpers.cs

https://github.com/signumsoftware/framework/blob/master/Signum.Web/HtmlHelpers/TabHelpers.cs




* A little bit more advanced, it has extension points to add tabs before or after other tabs using ViewOverrides. 

https://github.com/signumsoftware/framework/blob/master/Signum.Web/Facades/Navigator.md

I will cover the second problem in the next answer

**Comment by olmobrutall** [comment]
so you want one tab with the search page and the other tab with what? 

You can not add tabs to a search page, but you can create a new page (with a new controller action) that has tabs,  and inside one tab a search control. 

Alternatively you can add the tabs and the search control to the view of an entity, if this is what you need.
