### ISSUE TITLE
present entity as a link in a grid column of another entity

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#53]
Hi Olmo and the community!
How do I achieve the effect of a link in a column?

**Comment by mapacheL** [comment]
When you say a grid column are you talking about a column in a search window or about creating a link referring an entity to put somewhere in a view?

**Comment by roiez** [comment]
a column in a search window, thank you

*From:* Luis Delgado [mailto:notifications@github.com]
*Sent:* Tuesday, January 05, 2016 2:58 PM
*To:* signumsoftware/framework
*Cc:* roiez
*Subject:* Re: [framework] present entity as a link in a grid column of
another entity (#53)



When you say a grid column are you talking about a column in a search
window or about creating a link referring an entity to put somewhere in a
view?

—
Reply to this email directly or view it on GitHub
<https://github.com/signumsoftware/framework/issues/53#issuecomment-168991977>
.

**Comment by olmobrutall** [comment]
linking to an entity is automatic with some conditions: 

* in the query, the columns should be a Lite<T> instead of just the name of the entity. For example `invoice.ToLite()`

* the entity type (in this case the invoice) should be registered with a view in EntitySettings. 

Also, if doesn't work keep in mind that 

* the entity should be of a navigable EntityKind (Main, Shared, System). It doesn't work with non navigable ones (String, SystemString, Part..)

* the user should have permissions

**Comment by olmobrutall** [comment]
If you want a link to a custom or external page, not an entity, you can use a custom column formatter. 

Example here https://github.com/signumsoftware/southwind/blob/master/Southwind.Web/Code/SouthwindClient.cs
