### ISSUE TITLE
how to create a view displaying an entity by Custom index

### ISSUE THREAD

**Issue by SimonCohenDev** [signumsoftware/framework#54]
I would like to create a view in the CRM , which displays an entity (‘Account’) not by its id but by a custom key (‘ExternalId’).
(The default views select the entity by the PrimaryKey field of Lite<Entity>, which does not show any other fields)
How do I use the framework to do it?

**Comment by olmobrutall** [comment]
When you say view you mean a query in the search control? Or a detail view in a .cshtml?

**Comment by SimonCohenDev** [comment]
I mean a detail view in a .cshtml

**Comment by olmobrutall** [comment]
So you mean hot to make an url like:

Myapp.com/account/{externalId} and show the entity. 

Or you mean how to visually hide the id and show the externalId instead? 

Sorry but I need more details to answer

**Comment by olmobrutall** [comment]
Assuming you want both: take a look at NavigationController.View and the pages NormalPage.cshtml and NormalControl.cshtml. 

This will show you how the plumbing of the framework works when you see an entity. You need understanding of MVC to follow it. 

 It can be simplified for your case because you don't need to work with abstract entities, but your concrete AccoutEntity, and you can remove things that you don't need like widgets or maybe even operations. 

Hope it helps.
