### ISSUE TITLE
Problem on debug

### ISSUE THREAD

**Issue by goldenauge** [signumsoftware/framework#637]
Hi Olmo,

i m trying since yesterday to fix this problem:
![image](https://github.com/signumsoftware/framework/assets/13727800/c2e8695a-e83b-490a-8952-8617170e914b)

i updated my project:
![image](https://github.com/signumsoftware/framework/assets/13727800/2a8eeb99-f525-409b-9f68-5aba8f0625a9)

do you have any hint for me?

Imad

**Comment by olmobrutall** [comment]
Hi Imad, 

Probably you have the solution in the Output window. Unfortunately the TSGenerator is not a MSBuild ITask but a full console application that is called, so when there is an error I can not write it in the error window. 

The reason is that `dotnet build` uses .net core msbuild but VS uses .Net Framework MSBuild and I had problems making it work in both cases.

Tell me if this fixes the issue.

Olmo

**Comment by goldenauge** [comment]
can you give me a hint or link how can i change it in VS or Solution?
