### ISSUE TITLE
Passing parameters from view to logic

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#68]
Hi Olmo and the community,
i have a send email button that triggers an entity operation on an entity details popup page. 
![image](https://cloud.githubusercontent.com/assets/13131520/13662390/b5e30f32-e6a2-11e5-86ff-6817d5dd734b.png)
<pre>new Graph<AccountEntity>.Execute(AccountOperation.SendEmail)
                {
                    AllowsNew = true,
                    Lite = false,
                    CanExecute = e =>
                    {
                        //make sure username and email are not nulls
                        return !string.IsNullOrEmpty(e.EMail) && !string.IsNullOrEmpty(e.UserName) ? null : "Email and user name are required to send an email";
                    },
                    Execute = (e, args) =>
                    {
                                //here i need to select an email template from a value passed from the client
                                SendEmail(args.TemplateType);
                     }
                }</pre>
When the send button is being clicked I need to pass the value selected in the adjacent dropdown (not part of the entity), to the logic class in order to apply a relevant email template. 
How can this be achieved?  
Thank you,
Roi

**Comment by olmobrutall** [comment]
Here are the Dragons :) 

In Order to do this you need to write you our controller and typescript file. 

You have Find some inspiration looking for OrderOperation.CreateOrderFromProducts and OrderOperation.Ship in

https://github.com/signumsoftware/southwind/blob/master/Southwind.Web/Scripts/Order.ts


https://github.com/signumsoftware/southwind/blob/master/Southwind.Web/Controllers/HomeController.cs

https://github.com/signumsoftware/southwind/blob/master/Southwind.Web/Code/SouthwindClient.cs

I hope this code becomes simpler to understand with Signum.React

**Comment by roiez** [comment]
Yes, I am reading the material, here be dragons indeed:)
