### ISSUE TITLE
How to get OperationLogs for a specific entity (EntityLine with ImplementedByAll)

### ISSUE THREAD

**Issue by mnumeijer** [signumsoftware/framework#72]
Is there an easy way to have all operations available for a specific entity in either the Omnobox or in a detail form / window of the entity itself ?
It seems calling OperationLogs() on the entity always returns zero rows.

**Comment by olmobrutall** [comment]
Hi Marcel,

`DiffLogClient` client registers a QuickLink for web.  

You can register a similar one  in your app or just star DiffLogClient / DiffLogLogic to see the diffs in any entity. 

`OperationLogs` extension method should work. It uses ImplementedByAll but this is old stuff. You sure the entity has OperationLogs ?

**Comment by mnumeijer** [comment]
The quicklink works but is there also an easy way to be able to use the target in the omnobox search control ?
![2016-03-24 14_19_21-operation logs](https://cloud.githubusercontent.com/assets/907291/14017994/73746a18-f1cb-11e5-8434-3c1e2fe4adb5.png)

Now you can only make a distinction between null and not null

**Comment by olmobrutall** [comment]
Oh, I know what you mean. 

First of all: 

Omnibox is the name of the autocomplete on the very top that lets you access queries, entities, etc. what you mean is the autocomplete (or typeahead) in the EntotyLine that is in the FilterBuilder of the SearchControl.

Back to the Problem: 

ImplementedByAll references (like OperationLog.Target) have been always second-class citizens for EntityLines: 
* You can show a value or null, remove an navigate works 
* Find or Create don't work. 
* It's also not clear how autocomplete/combobox should work.

What you think the behavior should be in this cases? It shouldn't be complicated to implement it now with React.  

Also could be interesting to cast an IBA query token to a particular type, like:

OperationLogs filters:
Target.(as Order).State = Cancelled

This is simpler now because react has auto-complete for query tokens so I can just show all the types.

**Comment by mnumeijer** [comment]
I think it would be nice if ImplementedByAll worked like ImplementedBy:

![2016-03-29 09_19_04-start](https://cloud.githubusercontent.com/assets/907291/14100707/baf973fc-f58f-11e5-8fb1-35a0ffbab0e4.png)

**Comment by olmobrutall** [comment]
But showing al possible types? Including exception, part entities, enums, symbols... It's kind of noisy isn't it?

**Comment by mnumeijer** [comment]
I think you only need to show the types for which operations have been registered.

**Comment by olmobrutall** [comment]
This is a good heuristic for OperationLog target, but not sure if it's good for any ImplementedByAll in general. 

For example ProcessLineEntity, EmailMessageEntity, ViewLogEntity... 

Also will be good to sole it at the query token level (to allow complex joins) and at the entity line level (to allow create/find/autocomplete).

There are some ImplementedBy fields that have 10 possible implementations and could have been implemented as ImplementedByAll if the UI weren't so limiting.

**Comment by olmobrutall** [comment]
Hi @mnumeijer 

The support for ImplementedByAll in EntityLine and QueryTokens is ready 🎉 🎉 

https://github.com/signumsoftware/framework/commit/662cd995e92d32df908d23b6afde3f6c8e8ad5e6
https://github.com/signumsoftware/framework/commit/1abdc0d871fff0b294a7052a63c70825a10cad52

Cheers!
