### ISSUE TITLE
Close email window on "Send" button clicked

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#80]
Hi Olmo and the community, 
I need to close the email window as soon as the send button is clicked, 
how do I go about it?

**Comment by olmobrutall** [comment]
Two tips: 

In Operations.ts defaultDelete closes the popup. Look at the code to learn how. 

You'll need to override EmailMessageOperation.Send using OperationSettings as we did for CreateMessage. 

Note: Even if the Operation is defined in Signum.Extensions you can override them since they are just lambdas in dictionaries, effectively creating some how of dependency injection infrastructure.

**Comment by roiez** [comment]
I thought so, but wasn't sure, since it is a part of the framework. Thank you Olmo.
