### ISSUE TITLE
React version upgrade

### ISSUE THREAD

**Issue by roiez** [signumsoftware/framework#84]
Hi Olmo,
when do you plan to release the React version of the framework?

**Comment by olmobrutall** [comment]
That depends on How brave you are :) 

* The framework is relatively stable since a month or so. There are changes, sometimes breaking changes but I think can started to be used already. 

* Most of the complicated extensions are there now, but there are still some missing ones. You can see the progress here: https://github.com/signumsoftware/framework/wiki/Signum-React

* then I'll have to polish the example application to have more interesting examples with orders, employees etc... And include React in Create Application in signumframework.com. Maybe another month. 

* finally I'll need to write some markdown documentation and if I still have energy some tutorial. Another month. 

So, I think it start to be ready, since the dependencies from your code to the extensions is usually pretty low, and then start the extensions as they get finished. 

You can clone Southwind on React branch to have an idea.

**Comment by roiez** [comment]
Thank you, will check out Southwind on React branch.

**Comment by ghockx1p** [comment]
Will the normal Signum.Web still get updates once Signum React is done?

**Comment by olmobrutall** [comment]
Signum React is the future moving forward because its easier to get out of the box and produces better applications, and I'm moving all the applications in working on to Signum React. 

Still, it's a big change that can not be done with just a few regexes, so my plan to move the applications forward is: 

* Update Southwind to use Signum React, so the new cloned applications will use it, removing the Signum Web version. Signum Windows will still be an option. 

* Provide code generators from entities to react

* Provide code converters from cshtml to tsx. (Transforming around  70% of the code). 

* Keep Signum.Web maintained for about a year to give the teams some flexibility about when to do the transition but still be able to get new Signum Engine fixes an features. 

During this year the cool new features will be implemented in React only, Signum Web will be only fixed when is broken, but pull request will be accepted if somebody wants to take charge of maintaining it/ improving it.
